from __future__ import annotations

API_URL = "https://v.anime1.me/api"
DEFAULT_OUTPUT_DIR_NAME = "Anime1_Download"

DEFAULT_CONCURRENCY = 3
DEFAULT_CONNECT_TIMEOUT = 10.0
DEFAULT_READ_TIMEOUT = 30.0
DEFAULT_RETRIES = 3
DEFAULT_BACKOFF = 0.5

DEFAULT_CHUNK_SIZE = 512 * 1024
DEFAULT_MAX_FILENAME_STEM_LENGTH = 180

PROGRESS_TITLE_MAX_LENGTH = 42

RETRY_STATUS_CODES = frozenset({429, 500, 502, 503, 504})
